openapi: 3.0.3
info:
  title: RSOC API
  version: 0.2.0
servers:
  - url: https://STG_SERVICE_URL  # replace with Cloud Run URL
paths:
  /api/health:
    get:
      summary: Health
      responses:
        '200':
          description: OK
  /api/health-db:
    get:
      summary: DB Health
      responses:
        '200':
          description: OK
# TODO (M2): tracking/convert with 401/422/429 & Idempotency-Key contract

---

## `docs/milestones.md`
מטרת הקובץ: תמונת מיילסטונים עם סטטוס (דף אחד).

```markdown
# Milestones — Status (as of 2025-09-18)

## M1 — DB & Health ✅
- Cloud Run (STG) live: `afs-rsoc-api-stg` — `/api/health` OK
- Cloud SQL Postgres connected
- Schema: `events`, `identities`, `conversions`, `outbox`
- Migrations applied
- Secrets: `DATABASE_URL_STG`, `RSOC_API_TOKEN_STG`
- Newman smoke (DB/Health) passed

## M2 — Hardening + Outbound CAPI Worker (in progress)
1) Auth + Validation (401/422) for tracking/convert  
2) Rate limiting (429) + headers  
3) Idempotency-Key for convert  
4) TraceId logging  
5) Outbound CAPI Worker (outbox → CAPI, retries, DLQ, metrics)  
6) CI: Newman (happy+401/422/429+idempotency), k6 baseline (p95/p99)  
7) Docs: OpenAPI/Redoc sync

> Order: 1→3→2→4→5→6→7
